global:
  nameOverride: snapcast

app-template:
  controllers:
    snapcast:
      containers:
        main:
          resources:
            requests:
              cpu: 1000m
              memory: 512Mi
            limits:
              memory: 1024Mi
          image:
              repository: ghcr.io/ownyourio/snapcast
              tag: latest
          env:
            #LOG_LEVEL: debug
            TZ: Etc/UTC
            HOME: /tmp/
      pod:
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
          runAsNonRoot: true
          fsGroup: 1000
          fsGroupChangePolicy: OnRootMismatch

  service:
    snapcast-http:
      type: LoadBalancer
      controller: snapcast
      # https://metallb.universe.tf/usage/#local-traffic-policy
      externalTrafficPolicy: Local
      ports:
        websocket:
          port: 1780
    snapcast:
      type: LoadBalancer
      controller: snapcast
      # https://metallb.universe.tf/usage/#local-traffic-policy
      externalTrafficPolicy: Local
      ports:
        stream:
          port: 1704
        control:
          port: 1705
        tcp:
          port: 4953

    roc-streaming:
      type: LoadBalancer
      externalTrafficPolicy: Local
      controller: snapcast
      ports:
        roc-rtp:
          port: 10001
          protocol: UDP
        roc-repair:
          port: 10002
          protocol: UDP
        roc-control:
          port: 10003

  ingress:
    snapserver:
      hosts:
        - host: &host "snapserver.local"
          paths: &paths
            - path: /
              service:
                identifier: snapcast-http
                port: websocket
      tls:
        - hosts:
            - *host
          secretName: wildcard-cert

  configMaps:
    snapserver-conf:
      data:
        snapserver.conf: |-
          [stream]
          source = process:///usr/bin/roc-recv?name=Roc&buffer=200&params=--target-latency 200ms --rate 48000 --output=file:- --output-format=s16 --source=rtp+rs8m://0.0.0.0:10001 --repair=rs8m://0.0.0.0:10002 --control=rtcp://0.0.0.0:10003
          source = process:///usr/bin/squeezelite?name=LMS&params=-n "LMS" -s home-logitech-media-server-lms -o - -a 16 -r 48000
          stream = tcp://0.0.0.0?name=TCP&port=4953
          source = pipe:///tmp/snapfifo?name=default
          stream = meta:///Roc/LMS/TCP/default?name=Stream&mode=recent
          buffer = 200
          #source = pipe:///tmp/rocsink?name=rocfile

          [http]
          doc_root = /usr/share/snapserver/snapweb

  persistence:
    tmp:
      enabled: true
      existingClaim: snapcast-tmp
    snapserver:
      type: configMap
      name: "{{ .Release.Name }}-snapcast-snapserver-conf"
      globalMounts:
        - path: /etc/snapserver.conf
          subPath: snapserver.conf