apiVersion: v2
name: traefik
version: 1.0.0
appVersion: 2.11.10
dependencies:
  - name: traefik
    version: 33.0.0
    repository: https://traefik.github.io/charts
  - name: appset-traefik-zerotrust
    version: 1.1.3
    repository: https://ownyourio.github.io/SpencersLab/
