domain: OVERRIDE_VIA_APPSET

proxy:
  middlewares: 
    entrypoint: "kube-system-geoblock@kubernetescrd,kube-system-crowdsec@kubernetescrd"
  # Additional values should be added via custom-values.
  subdomains:
    login:
      enabled: true
      paths:
        - /realms/SpencersLab/
        - /resources/
    registration:
      enabled: true

    # These have apps & SSO
    player:
      enabled: true
    audiobook-player:
      enabled: true
    pictures:
    documents:
    music-player:
    #home:

    # Just SSO
    boards:
      enabled: true
    git:
    charts:
    #esphome:

    # Services with no account support. (Auth should be added at proxy-local)
    torrents:
      enabled: true
    requests:
      enabled: true
    music:
      enabled: true
    shows:
      enabled: true
    movies:
      enabled: true
    ebooks:
      enabled: true
    audiobooks:
      enabled: true
    streams:
      enabled: true
    stream:
      enabled: true

sshd:
  global:
    nameOverride: "sshd"
  controllers:
    main:
      containers:
        main:
          image:
            repository: ghcr.io/linuxserver/openssh-server
            tag: 9.7_p1-r4-ls171
          env:
            TZ: America/Denver
            PUID: 2000
            PGID: 2000
            PUBLIC_KEY: OVERRIDE_VIA_CUSTOM_VALUES
            #PUBLIC_KEY_DIR:
            USER_NAME: proxy
            DOCKER_MODS: linuxserver/mods:openssh-server-ssh-tunnel

          resources:
            requests:
              cpu: 500m
              memory: 0.2Gi
            limits:
              memory: 4Gi
      pod:
        securityContext:
          # Have to run as root otherwise it can't create the proxy user.
          #runAsUser: 2000
          #runAsGroup: 2000
          fsGroup: 2000
          fsGroupChangePolicy: "OnRootMismatch"

  service:
    ssh:
      type: LoadBalancer
      externalTrafficPolicy: Local
      controller: main
      ports:
        ssh:
          port: 2222
          protocol: TCP
          targetPort: 2222

  persistence:
    sshd:
      existingClaim: sshd
      globalMounts:
        - path: /config/ssh_host_keys
