apiVersion: v2
name: monitoring-agent
version: 1.0.11
appVersion: 1.0.0
dependencies:
- name: kube-prometheus-stack
  version: 67.11.0
  repository: https://prometheus-community.github.io/helm-charts
