{{ if .Values.autoUpdateK3s }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: system-upgrade-controller
  namespace: default
spec:
  project: default
  source:
    repoURL: https://github.com/rancher/system-upgrade-controller
    # TODO: Make sure this is getting updated. Originally was v0.14.2
    targetRevision: v0.14.2
    path: manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: system-upgrade
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
...
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: system-upgrade-controller-role
rules:
- apiGroups: ['']
  resources: ['namespaces']
  verbs: ['get', 'list']
  resourceNames: ['kube-system']  # Explicitly allow access to kube-system
- apiGroups: ['']
  resources: ['nodes']
  verbs: ['get', 'list', 'patch', 'update']
- apiGroups: ['batch']
  resources: ['jobs']
  verbs: ['create', 'delete', 'get', 'list', 'watch']
- apiGroups: ['apps']
  resources: ['daemonsets']
  verbs: ['get', 'list']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: system-upgrade-controller-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system-upgrade-controller-role
subjects:
- kind: ServiceAccount
  name: system-upgrade
  namespace: system-upgrade
...
{{ end }}
