apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: traefik-appset
spec:
  generators:
    # Generator for apps that should deploy to all cluster.
    - matrix:
        generators:
          - clusters: {}
          - list:
              elements:
                - appName: traefik
                  namespace: kube-system
                  ServerSideApply: "false"
  template:
    metadata:
      name: "{{ `{{appName}}` }}"
      annotations:
        argocd.argoproj.io/manifest-generate-paths: ".;.."
    spec:
      project: default
      source:
        repoURL: "{{ `{{ metadata.annotations.services.repo }}` }}"
        targetRevision: main
        path: "{{ `{{ metadata.annotations.services.repo.path }}`}}/{{ `{{appName}}` }}/{{ `{{ metadata.annotations.stage }}` }}"
        helm:
          #parameters:
          #  - name: domain
          #    value: "{{ `{{ metadata.annotations.domain }}` }}"
          #  - name: clusterName
          #    value: "{{ `{{ metadata.annotations.clusterName }}` }}"
          valueFiles:
        #    #- ../common.values.yaml
            - values.yaml
      destination:
        name: "{{ `{{name}}` }}"
        namespace: "{{ `{{namespace}}` }}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          # Needed for: https://github.com/prometheus-community/helm-charts/issues/3345
          - ServerSideApply={{ `{{ServerSideApply}}` }}
