apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd
  namespace: default
  labels:
    app: default
  annotations:
    kubernetes.io/ingress.class: "traefik"
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    #traefik.ingress.kubernetes.io/router.middlewares: authentik-authentik-middleware@kubernetescrd
spec:
  tls:
  - hosts:
      - "cluster.{{ $.Values.clusterName }}.{{ $.Values.domain }}"
    secretName: cluster-wildcard-cert
  rules:
    - host: "cluster.{{ $.Values.clusterName }}.{{ $.Values.domain }}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: "{{ .Release.Name }}-argocd-server"
                port:
                  number: 80
#---
#apiVersion: traefik.containo.us/v1alpha1
#kind: Middleware
#metadata:
#  name: authentik-middleware
#  namespace: authentik
#spec:
#  forwardAuth:
#    address: http://authentik:9000/outpost.goauthentik.io/auth/traefik
#    trustForwardHeader: true
#    authResponseHeaders:
#      - X-authentik-username
#      - X-authentik-groups
#      - X-authentik-email
#      - X-authentik-name
#      - X-authentik-uid
#      - X-authentik-jwt
#      - X-authentik-meta-jwks
#      - X-authentik-meta-outpost
#      - X-authentik-meta-provider
#      - X-authentik-meta-app
#      - X-authentik-meta-version
