global:
  nameOverride: ledfx
bitwardenIds:
  ledfx: OVERRIDE_NEEDED
app-template:
  controllers:
    ledfx:
      annotations:
        reloader.stakater.com/auto: "true"
      containers:
        main:
          image:
            repository: ghcr.io/mchestr/ledfx
            tag: v2.0.97
          env:
            TZ: Etc/UTC
            HOST: ledfx.local
          #envFrom:
          #  - secretRef:
          #      name: ledfx-secret
          probes:
            liveness: &probes
              enabled: true
              custom: true
              spec:
                httpGet:
                  path: /api/info
                  port: &port 8888
                initialDelaySeconds: 0
                periodSeconds: 10
                timeoutSeconds: 1
                failureThreshold: 3
            readiness: *probes
            startup:
              enabled: false
          resources:
            requests:
              cpu: 10m
              memory: 250Mi
            limits:
              memory: 1000Mi
          #securityContext:
          #  allowPrivilegeEscalation: false
          #  readOnlyRootFilesystem: true
          #  capabilities:
          #    drop:
          #      - ALL
      #pod:
      #  securityContext:
      #    # Needs to run as root?
      #    runAsUser: 568
      #    runAsNonRoot: true
      #    fsGroup: 568
      #    fsGroupChangePolicy: OnRootMismatch
          #supplementalGroups:
          #  # Dialout on MicroOS
          #  - 492 
          #  - 20
  service:
    ledfx:
      controller: ledfx
      ports:
        http:
          port: *port 
  ingress:
    ledfx:
      #annotations:
      hosts:
        - host: &host "ledfx.local"
          paths: &paths
            - path: /
              service:
                identifier: ledfx
                port: http
        - host: &customHost ledfx.local
          paths: *paths
      tls:
        - hosts:
            - *host
            - *customHost
  persistence:
    config:
      existingClaim: ledfx
      globalMounts:
        - path: /app/ledfx-config
